services:
  database:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_database:/data/db
    networks:
      - three-tier
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  backend:
    container_name: backend
    image: backend:v1
    ports:
      - "5000:5000"
    networks:
      - three-tier
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    image: frontend:v1
    ports:
      - "8080:80"
    networks:
      - three-tier
    depends_on:
      - backend

volumes:
  mongo_database:
networks:
  three-tier:
