apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: three-tier-dev
spec:
  selector:
    app: backend
  ports:
  - name: backend-svc
    protocol: TCP
    port: 5000
    targetPort: 5000