apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: three-tier-dev
data:
  MONGO_URI: mongodb://username01:password01@mongodb-svc:27017/snakegame?authSource=admin
  PORT: "5000"
