apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: three-tier-dev
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: akifmhd/backend:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
      