apiVersion: v1
kind: PersistentVolumeCliam
metadata:
  name: mongodb-volume-claim
  namespace: three-tier-dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi